version: '3'
services:
  # frontend:
  backend:
    build: ./backend
    networks:
      - internal
    volumes:
      - ./backend:/project
    working_dir: /project
    command:
      - sh
      - -c
      - >
        ./manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
  psql:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: f360
    networks:
      - internal

networks:
  internal: