version: '3'
services:
  # frontend:
  backend:
    image: python:3.6-alpine
    networks:
      - internal
    volumes:
      - ./backend:/project
    working_dir: /project
    command:
      - sh
      - -c
      - >
        pip install -r requirements.txt &&
        ./manage.py runserver
    ports:
      - 8000:8000
  psql:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: toor
    networks:
      - internal

networks:
  internal: